### ISSUE TITLE
trio support does not work

### ISSUE THREAD

**Issue by PJ-Schulz** [alex-oleshkevich/mailers#1]
Hello,

in your description you have written, that the package supports trio with anyio. But when I use it with trio I get the Exception:
`TypeError: trio.run received unrecognized yield message <Future pending>. Are you trying to use a library written for some other framework like asyncio? That won't work without some kind of compatibility shim`

I saw that you use ` aiosmtplib.send` for sending the mail, but that wont work with trio.

https://github.com/alex-oleshkevich/mailers/blob/7353cd8224e8016188dbf1469d1a89e2b1989ac3/mailers/transports/smtp.py#L31-L42

**Comment by alex-oleshkevich** [comment]
Sorry for that!
I will update the documentation.
