### ISSUE TITLE
Markdown & premailer support

### ISSUE THREAD

**Issue by iloveitaly** [alex-oleshkevich/mailers#11]
Hello! Thanks for the great library. Wondering if you've been open to two additions:

* markdown preprocessor. Or is this sort of the thing better handled upstream by a jinja extension? https://github.com/mkbabb/jinja-markdown2
* [css_inliner support](https://github.com/Stranger6667/css-inline/tree/master/bindings/python). The existing css_inliner could be extended to detect if premailer is installed and use that instead.

I've done this before with another project, so I'd be porting code that looks something like this:

https://github.com/iloveitaly/todoist-digest/blob/master/todoist_digest/email.py

**Comment by alex-oleshkevich** [comment]
Yes, that would be a great add-on.
I am even pro replacing toronado (current css inliner) with premailer.

As of markdown. What are benefits of using jinja-markdown comparing to classing Markdown -> HTML flow?

**Comment by iloveitaly** [comment]
Honestly, not sure. I think a more direct markdown => HTML flow would be cleaner.

Great, I'll go ahead and replace with css_inliner.
