### ISSUE TITLE
`aiosmtplib` not actually optional

### ISSUE THREAD

**Issue by wolfskaempf** [alex-oleshkevich/mailers#3]
Due to `from mailers.transports.smtp import SMTPTransport` inside `mailers/__init__.py` the module `mailers.transports.smtp` gets initialised in all cases. `mailers/transports/smtp.py` contains `import aiosmtplib`. Therefore, if `aiosmtplib` is not installed, attempting to use `mailers` will always result in a `ModuleNotFoundError: No module named 'aiosmtplib'`.

Since there are multiple ways to address this I have not created a PR, but I'm happy to implement a solution for this that you agree will be most useful.

- Option 1: Make `aiosmtplib` mandatory
- Option 2: Change how `mailers` works to make `aiosmtplib` actually optional.

Sidenote on how I discovered this: After switching to the latest release (thanks btw!) I had to re-add the dependency to my project. Inside the `README.md` it says to `pip install mailers[aiosmtplib]` but it should actually be `pip install mailers[smtp]` according to the definition in `pyproject.toml`.

```toml
[tool.poetry.extras]
jinja2 = ["jinja2"]
smtp = ["aiosmtplib"]
dkim = ["dkimpy"]
```

Same here, the solution could be to either change `smtp` to `aiosmtplib` or to update the `README.md` to state `pip install mailers[smtp]`.

Let me know which solutions you prefer and I'm happy to submit a PR to implement them.

**Comment by alex-oleshkevich** [comment]
I think the best would be to do inline import in the transport before this line https://github.com/alex-oleshkevich/mailers/blob/847d0e3024ff89bc9b96cd8a70c05d4818abe625/mailers/transports/smtp.py#L32

this won't be a breaking change.

**Comment by wolfskaempf** [comment]
@alex-oleshkevich Currently there is still the documentation and configuration mismatch between what the optional selector is called. Should the `README.md` be updated to say `pip install mailers[smtp]` to avoid a breaking change in the configuration (to make the current instructions work)? I can offer to update the `README.md` in PR #4 or in a separate PR. Let me know what you prefer.

**Comment by alex-oleshkevich** [comment]
Yes, please. You can do this in #4, I have no strong preferences on this.

**Comment by wolfskaempf** [comment]
@alex-oleshkevich Updated the installation instructions. #4 is ready for review.

**Comment by alex-oleshkevich** [comment]
thank you!
