### ISSUE TITLE
css_inliner bug

### ISSUE THREAD

**Issue by canardoFR** [alex-oleshkevich/mailers#8]
Hi,

when adding an inline image, css_inliner is not working because "multipart/related" is missing in a list.

line 21 of cssliner.py should be
    if message.get_content_type() in ["multipart/alternative", "multipart/mixed", "multipart/related"]:

Cheers,
   Alain R.
   
   PS. Still willing to correct all issues if I can manage a pull

**Comment by alex-oleshkevich** [comment]
Just fork the repo, make changes and submit Pull Request.
Thanks!
